-- =========================================
-- بيانات المنتجات الحالية (تم استخراجها من الموقع تلقائياً)
-- العدد الكلي: 227 منتج
-- =========================================

INSERT INTO products (name, price, image, category_page, category_tag, colors_count, sort_order, in_stock) VALUES
('حقيبة ظهر كاجوال', 28.0, 'image/حقائب ظهر/bag-backpack-1.jpg.png', 'bags', 'backpack', 1, 1, true),
('حقيبة ظهر جلد', 42.0, 'image/حقائب ظهر/bag-backpack-2.jpg.png', 'bags', 'backpack', 1, 2, true),
('حقيبة ظهر قماش', 25.0, 'image/حقائب ظهر/bag-backpack-3.jpg.png', 'bags', 'backpack', 1, 3, true),
('حقيبة ظهر مدرسية', 30.0, 'image/حقائب ظهر/bag-backpack-4.jpg.png', 'bags', 'backpack', 1, 4, true),
('حقيبة ظهر صغيرة', 26.0, 'image/حقائب ظهر/bag-backpack-5.jpg.png', 'bags', 'backpack', 1, 5, true),
('حقيبة ظهر رياضية', 32.0, 'image/حقائب ظهر/bag-backpack-6.jpg.png', 'bags', 'backpack', 1, 6, true),
('حقيبة كتف جلد', 38.0, 'image/حقائب كتف/bag-shoulder-1.jpg.png', 'bags', 'shoulder', 1, 7, true),
('حقيبة كتف كلاسيكية', 35.0, 'image/حقائب كتف/bag-shoulder-2.jpg.png', 'bags', 'shoulder', 1, 8, true),
('حقيبة كتف متوسطة', 32.0, 'image/حقائب كتف/bag-shoulder-3.jpg.jpg', 'bags', 'shoulder', 1, 9, true),
('حقيبة كتف شيك', 40.0, 'image/حقائب كتف/bag-shoulder-4.jpg.png', 'bags', 'shoulder', 1, 10, true),
('حقيبة كتف يومية', 30.0, 'image/حقائب كتف/bag-shoulder-5.jpg.png', 'bags', 'shoulder', 1, 11, true),
('حقيبة كتف عصرية', 36.0, 'image/حقائب كتف/bag-shoulder-6.jpg.png', 'bags', 'shoulder', 1, 12, true),
('حقيبة كروس صغيرة', 22.0, 'image/حقائب كروس/bag-crossbody-1.jpg.png', 'bags', 'crossbody', 1, 13, true),
('حقيبة كروس جلد', 30.0, 'image/حقائب كروس/bag-crossbody-2.jpg.png', 'bags', 'crossbody', 1, 14, true),
('حقيبة كروس عملية', 24.0, 'image/حقائب كروس/bag-crossbody-3.jpg.png', 'bags', 'crossbody', 1, 15, true),
('حقيبة كروس أنيقة', 28.0, 'image/حقائب كروس/bag-crossbody-4.jpg.png', 'bags', 'crossbody', 1, 16, true),
('حقيبة كروس كاجوال', 21.0, 'image/حقائب كروس/bag-crossbody-5.jpg.png', 'bags', 'crossbody', 1, 17, true),
('حقيبة كروس مطرزة', 27.0, 'image/حقائب كروس/bag-crossbody-6.jpg.png', 'bags', 'crossbody', 1, 18, true),
('حقيبة توت واسعة', 34.0, 'image/حقائب توت/bag-tote-1.jpg.png', 'bags', 'tote', 1, 19, true),
('حقيبة توت جامعية', 29.0, 'image/حقائب توت/bag-tote-2.jpg.png', 'bags', 'tote', 1, 20, true),
('حقيبة توت قماش', 26.0, 'image/حقائب توت/bag-tote-3.jpg.png', 'bags', 'tote', 1, 21, true),
('حقيبة توت جلد', 45.0, 'image/حقائب توت/bag-tote-4.jpg.png', 'bags', 'tote', 1, 22, true),
('حقيبة توت كبيرة', 38.0, 'image/حقائب توت/bag-tote-5.jpg.png', 'bags', 'tote', 1, 23, true),
('حقيبة توت يومية', 31.0, 'image/حقائب توت/bag-tote-6.jpg.png', 'bags', 'tote', 1, 24, true),
('كلتش سهرة', 24.0, 'image/حقائب كلتش/bag-clutch-1.jpg.png', 'bags', 'clutch', 1, 25, true),
('كلتش لامع', 26.0, 'image/حقائب كلتش/bag-clutch-2.jpg.png', 'bags', 'clutch', 1, 26, true),
('كلتش مطرز', 30.0, 'image/حقائب كلتش/bag-clutch-3.jpg.png', 'bags', 'clutch', 1, 27, true),
('كلتش صغير أنيق', 22.0, 'image/حقائب كلتش/bag-clutch-4.jpg.png', 'bags', 'clutch', 1, 28, true),
('كلتش ذهبي', 28.0, 'image/حقائب كلتش/bag-clutch-5.jpg.png', 'bags', 'clutch', 1, 29, true),
('كلتش كلاسيكي', 25.0, 'image/حقائب كلتش/لقطة الشاشة 2026-08-30 143059.png', 'bags', 'clutch', 1, 30, true),
('فستان كاجوال قطن', 25.0, 'image/فساتين%20كاجوال/dress-casual-1.jpg', 'dresses', 'casual', 1, 1, true),
('فستان يومي بسيط', 28.0, 'image/فساتين%20كاجوال/dress-casual-2.jpg', 'dresses', 'casual', 1, 2, true),
('فستان كاجوال مقلم', 30.0, 'image/فساتين%20كاجوال/dress-casual-3.jpg', 'dresses', 'casual', 1, 3, true),
('فستان قصير كاجوال', 32.0, 'image/فساتين%20كاجوال/dress-casual-4.jpg', 'dresses', 'casual', 1, 4, true),
('فستان كاجوال واسع', 22.0, 'image/فساتين%20كاجوال/dress-casual-5.jpg', 'dresses', 'casual', 1, 5, true),
('فستان قطن مريح', 27.0, 'image/فساتين%20كاجوال/dress-casual-6.jpg', 'dresses', 'casual', 1, 6, true),
('فستان يومي أنيق', 33.0, 'image/فساتين%20كاجوال/dress-casual-7.jpg', 'dresses', 'casual', 1, 7, true),
('فستان كاجوال باستيل', 29.0, 'image/فساتين%20كاجوال/dress-casual-8.jpg', 'dresses', 'casual', 1, 8, true),
('فستان صيفي مطبع', 30.0, 'image/فساتين%20صيفي/dress-summer-1.jpg', 'dresses', 'summer', 1, 9, true),
('فستان شيفون صيفي', 35.0, 'image/فساتين%20صيفي/dress-summer-2.jpg', 'dresses', 'summer', 1, 10, true),
('فستان صيفي مزهر', 32.0, 'image/فساتين%20صيفي/dress-summer-3.jpg', 'dresses', 'summer', 1, 11, true),
('فستان صيفي بدون أكمام', 38.0, 'image/فساتين%20صيفي/dress-summer-4.jpg', 'dresses', 'summer', 1, 12, true),
('فستان صيفي فاتح', 34.0, 'image/فساتين%20صيفي/dress-summer-5.jpg', 'dresses', 'summer', 1, 13, true),
('فستان صيفي منقط', 40.0, 'image/فساتين%20صيفي/dress-summer-6.jpg', 'dresses', 'summer', 1, 14, true),
('فستان صيفي خفيف', 36.0, 'image/فساتين%20صيفي/dress-summer-7.jpg', 'dresses', 'summer', 1, 15, true),
('فستان صيفي ملون', 33.0, 'image/فساتين%20صيفي/dress-summer-8.jpg', 'dresses', 'summer', 1, 16, true),
('فستان محجبات طويل', 45.0, 'image/فساتين%20محجبات/dress-modest-1.jpg', 'dresses', 'modest', 1, 17, true),
('فستان محجبات كم طويل', 50.0, 'image/فساتين%20محجبات/dress-modest-2.jpg', 'dresses', 'modest', 1, 18, true),
('فستان محجبات أنيق', 42.0, 'image/فساتين%20محجبات/dress-modest-3.jpg', 'dresses', 'modest', 1, 19, true),
('فستان محجبات واسع', 55.0, 'image/فساتين%20محجبات/dress-modest-4.jpg', 'dresses', 'modest', 1, 20, true),
('فستان محجبات مطرز', 48.0, 'image/فساتين%20محجبات/dress-modest-5.jpg', 'dresses', 'modest', 1, 21, true),
('فستان محجبات كلاسيكي', 52.0, 'image/فساتين%20محجبات/dress-modest-6.jpg', 'dresses', 'modest', 1, 22, true),
('فستان محجبات فاخر', 46.0, 'image/فساتين%20محجبات/dress-modest-7.jpg', 'dresses', 'modest', 1, 23, true),
('فستان مطرز', 45.0, 'image/فساتين%20مناسبات/dress-occasions-1.jpg', 'dresses', 'occasions', 1, 24, true),
('فستان مناسبات أنيق', 50.0, 'image/فساتين%20مناسبات/dress-occasions-2.jpg', 'dresses', 'occasions', 1, 25, true),
('فستان ميدي فاخر', 55.0, 'image/فساتين%20مناسبات/dress-occasions-3.jpg', 'dresses', 'occasions', 1, 26, true),
('فستان مناسبات مطرز', 48.0, 'image/فساتين%20مناسبات/dress-occasions-4.jpg', 'dresses', 'occasions', 1, 27, true),
('فستان مناسبات كلاسيكي', 52.0, 'image/فساتين%20مناسبات/dress-occasions-5.jpg', 'dresses', 'occasions', 1, 28, true),
('فستان سواريه خفيف', 60.0, 'image/فساتين%20مناسبات/dress-occasions-6.jpg', 'dresses', 'occasions', 1, 29, true),
('فستان مناسبات مميز', 47.0, 'image/فساتين%20مناسبات/dress-occasions-7.jpg', 'dresses', 'occasions', 1, 30, true),
('فستان مناسبات راقي', 53.0, 'image/فساتين%20مناسبات/dress-occasions-8.jpg', 'dresses', 'occasions', 1, 31, true),
('فستان مناسبات عصري', 58.0, 'image/فساتين%20مناسبات/dress-occasions-9.jpg', 'dresses', 'occasions', 1, 32, true),
('فستان سهرة كلاسيكي', 60.0, 'image/فساتين%20سهرة/dress-evening-1.jpg', 'dresses', 'evening', 1, 33, true),
('فستان سهرة طويل أنيق', 65.0, 'image/فساتين%20سهرة/dress-evening-2.jpg', 'dresses', 'evening', 1, 34, true),
('فستان سهرة لامع', 70.0, 'image/فساتين%20سهرة/dress-evening-3.jpg', 'dresses', 'evening', 1, 35, true),
('فستان سهرة ساتان', 58.0, 'image/فساتين%20سهرة/dress-evening-4.jpg', 'dresses', 'evening', 1, 36, true),
('فستان سهرة دانتيل', 75.0, 'image/فساتين%20سهرة/dress-evening-5.jpg', 'dresses', 'evening', 1, 37, true),
('فستان سهرة فاخر', 62.0, 'image/فساتين%20سهرة/dress-evening-6.jpg', 'dresses', 'evening', 1, 38, true),
('فستان سهرة أسود', 68.0, 'image/فساتين%20سهرة/dress-evening-7.jpg', 'dresses', 'evening', 1, 39, true),
('فستان سهرة ذهبي', 80.0, 'image/فساتين%20سهرة/dress-evening-8.jpg', 'dresses', 'evening', 1, 40, true),
('هيلز كلاسيك أسود', 30.0, 'image/هيلزات/هيلز كلاسيك/heel-classic-1.jpg.png', 'heels', 'classic', 1, 1, true),
('هيلز كلاسيك جلد', 34.0, 'image/هيلزات/هيلز كلاسيك/heel-classic-2.jpg.png', 'heels', 'classic', 1, 2, true),
('هيلز كلاسيك مغلق', 32.0, 'image/هيلزات/هيلز كلاسيك/heel-classic-3.jpg.png', 'heels', 'classic', 1, 3, true),
('هيلز كلاسيك أنيق', 36.0, 'image/هيلزات/هيلز كلاسيك/heel-classic-4.jpg.png', 'heels', 'classic', 1, 4, true),
('هيلز كلاسيك يومي', 28.0, 'image/هيلزات/هيلز كلاسيك/heel-classic-5.jpg.png', 'heels', 'classic', 1, 5, true),
('صندل هيلز سهرة', 32.0, 'image/هيلزات/هيلز صنادل/heel-open-1.jpg.png', 'heels', 'open', 1, 6, true),
('صندل هيلز مفتوح', 30.0, 'image/هيلزات/هيلز صنادل/heel-open-2.jpg.png', 'heels', 'open', 1, 7, true),
('صندل هيلز مزين', 35.0, 'image/هيلزات/هيلز صنادل/heel-open-3.jpg.png', 'heels', 'open', 1, 8, true),
('صندل هيلز صيفي', 29.0, 'image/هيلزات/هيلز صنادل/heel-open-4.jpg.png', 'heels', 'open', 1, 9, true),
('صندل هيلز أنيق', 33.0, 'image/هيلزات/هيلز صنادل/heel-open-5.jpg.png', 'heels', 'open', 1, 10, true),
('هيلز كعب عريض مريح', 34.0, 'image/هيلزات/هيلز كعب عريض/heel-wideheel-1.jpg.png', 'heels', 'wideheel', 1, 11, true),
('هيلز كعب عريض كلاسيك', 36.0, 'image/هيلزات/هيلز كعب عريض/heel-wideheel-2.jpg.png', 'heels', 'wideheel', 1, 12, true),
('هيلز كعب عريض جلد', 38.0, 'image/هيلزات/هيلز كعب عريض/heel-wideheel-3.jpg.png', 'heels', 'wideheel', 1, 13, true),
('هيلز كعب عريض يومي', 30.0, 'image/هيلزات/هيلز كعب عريض/heel-wideheel-4.jpg.png', 'heels', 'wideheel', 1, 14, true),
('هيلز كعب عريض أنيق', 37.0, 'image/هيلزات/هيلز كعب عريض/heel-wideheel-5.jpg.png', 'heels', 'wideheel', 1, 15, true),
('هيلز كعب رفيع ستيلتو', 38.0, 'image/هيلزات/هيلز كعب رفيع/heel-thinheel-1.jpg.png', 'heels', 'thinheel', 1, 16, true),
('هيلز كعب رفيع سهرة', 40.0, 'image/هيلزات/هيلز كعب رفيع/heel-thinheel-2.jpg.png', 'heels', 'thinheel', 1, 17, true),
('هيلز كعب رفيع أنيق', 36.0, 'image/هيلزات/هيلز كعب رفيع/heel-thinheel-3.jpg.png', 'heels', 'thinheel', 1, 18, true),
('هيلز كعب رفيع لامع', 42.0, 'image/هيلزات/هيلز كعب رفيع/heel-thinheel-4.jpg.png', 'heels', 'thinheel', 1, 19, true),
('هيلز كعب رفيع كلاسيك', 35.0, 'image/هيلزات/هيلز كعب رفيع/heel-thinheel-5.jpg.png', 'heels', 'thinheel', 1, 20, true),
('هيلز مفتوح من الخلف', 33.0, 'image/هيلزات/هيلز مفتوح خلف/heel-openback-1.jpg.png', 'heels', 'openback', 1, 21, true),
('هيلز سلينج باك', 34.0, 'image/هيلزات/هيلز مفتوح خلف/heel-openback-2.jpg.png', 'heels', 'openback', 1, 22, true),
('هيلز مفتوح خلف أنيق', 36.0, 'image/هيلزات/هيلز مفتوح خلف/heel-openback-3.jpg.png', 'heels', 'openback', 1, 23, true),
('هيلز مفتوح خلف سهرة', 39.0, 'image/هيلزات/هيلز مفتوح خلف/heel-openback-4.jpg.png', 'heels', 'openback', 1, 24, true),
('هيلز مفتوح خلف يومي', 31.0, 'image/هيلزات/هيلز مفتوح خلف/heel-openback-5.jpg.png', 'heels', 'openback', 1, 25, true),
('سنيكرز أبيض كلاسيك', 32.0, 'image/أحذية سنيكرز/shoe-sneakers-1.jpg.png', 'shoes', 'sneakers', 1, 1, true),
('سنيكرز كاجوال ملون', 30.0, 'image/أحذية سنيكرز/shoe-sneakers-2.jpg.png', 'shoes', 'sneakers', 1, 2, true),
('سنيكرز جلد', 38.0, 'image/أحذية سنيكرز/shoe-sneakers-3.jpg.png', 'shoes', 'sneakers', 1, 3, true),
('سنيكرز كاجوال خفيف', 28.0, 'image/أحذية سنيكرز/shoe-sneakers-4.jpg.png', 'shoes', 'sneakers', 1, 4, true),
('سنيكرز مطرز', 35.0, 'image/أحذية سنيكرز/shoe-sneakers-5.jpg.png', 'shoes', 'sneakers', 1, 5, true),
('سنيكرز يومي مريح', 27.0, 'image/أحذية سنيكرز/لقطة الشاشة 2026-08-31 181908.png', 'shoes', 'sneakers', 1, 6, true),
('كوتش رياضي جري', 40.0, 'image/أحذية رياضية/shoe-athletic-1.jpg.png', 'shoes', 'athletic', 1, 7, true),
('كوتش تمارين خفيف', 36.0, 'image/أحذية رياضية/shoe-athletic-2.jpg.png', 'shoes', 'athletic', 1, 8, true),
('كوتش رياضي تهوية', 38.0, 'image/أحذية رياضية/shoe-athletic-3.jpg.png', 'shoes', 'athletic', 1, 9, true),
('كوتش رياضي داعم', 45.0, 'image/أحذية رياضية/shoe-athletic-4.jpg.png', 'shoes', 'athletic', 1, 10, true),
('كوتش رياضي ملون', 34.0, 'image/أحذية رياضية/shoe-athletic-5.jpg.png', 'shoes', 'athletic', 1, 11, true),
('كوتش رياضي احترافي', 50.0, 'image/أحذية رياضية/لقطة الشاشة 2026-08-31 182734.png', 'shoes', 'athletic', 1, 12, true),
('سليب أون كلاسيك', 26.0, 'image/أحذية مسطحة/shoe-slipon-1.jpg.png', 'shoes', 'slipon', 1, 13, true),
('حذاء مسطح جلد', 30.0, 'image/أحذية مسطحة/shoe-slipon-2.jpg.png', 'shoes', 'slipon', 1, 14, true),
('لوفر أنيق', 32.0, 'image/أحذية مسطحة/shoe-slipon-3.jpg.png', 'shoes', 'slipon', 1, 15, true),
('سليب أون قماش', 22.0, 'image/أحذية مسطحة/shoe-slipon-4.jpg.png', 'shoes', 'slipon', 1, 16, true),
('حذاء مسطح مخملي', 28.0, 'image/أحذية مسطحة/shoe-slipon-5.jpg.png', 'shoes', 'slipon', 1, 17, true),
('لوفر كاجوال', 25.0, 'image/أحذية مسطحة/لقطة الشاشة 2026-08-31 183206.png', 'shoes', 'slipon', 1, 18, true),
('بوت كاجوال جلد', 48.0, 'image/أحذية بوت/shoe-boots-1.jpg.png', 'shoes', 'boots', 1, 19, true),
('هاف بوت شتوي', 42.0, 'image/أحذية بوت/shoe-boots-2.jpg.png', 'shoes', 'boots', 1, 20, true),
('بوت كاحل أنيق', 40.0, 'image/أحذية بوت/shoe-boots-3.jpg.png', 'shoes', 'boots', 1, 21, true),
('بوت كاجوال مطاطي', 36.0, 'image/أحذية بوت/shoe-boots-4.jpg.png', 'shoes', 'boots', 1, 22, true),
('هاف بوت سويدي', 50.0, 'image/أحذية بوت/shoe-boots-5.jpg.png', 'shoes', 'boots', 1, 23, true),
('بوت كعب منخفض', 44.0, 'image/أحذية بوت/لقطة الشاشة 2026-08-31 183618.png', 'shoes', 'boots', 1, 24, true),
('جينز ضيق كلاسيك', 26.0, 'image/جينزات/جينز ضيق/jean-skinny-1.jpg.png', 'jeans', 'skinny', 1, 1, true),
('جينز ضيق قصة عصرية', 28.0, 'image/جينزات/جينز ضيق/jean-skinny-2.jpg.png', 'jeans', 'skinny', 1, 2, true),
('جينز ضيق خصر عالي', 30.0, 'image/جينزات/جينز ضيق/jean-skinny-3.jpg.png', 'jeans', 'skinny', 1, 3, true),
('جينز ضيق أسود', 27.0, 'image/جينزات/جينز ضيق/jean-skinny-4.jpg.png', 'jeans', 'skinny', 1, 4, true),
('جينز ضيق كحلي', 29.0, 'image/جينزات/جينز ضيق/jean-skinny-5.jpg.png', 'jeans', 'skinny', 1, 5, true),
('جينز ضيق ممزق خفيف', 31.0, 'image/جينزات/جينز ضيق/jean-skinny-6.jpg.png', 'jeans', 'skinny', 1, 6, true),
('جينز مستقيم كلاسيك', 28.0, 'image/جينزات/جينز مستقيم/jean-straight-1.jpg.png', 'jeans', 'straight', 1, 7, true),
('جينز مستقيم خصر عالي', 30.0, 'image/جينزات/جينز مستقيم/jean-straight-2.jpg.png', 'jeans', 'straight', 1, 8, true),
('جينز مستقيم أزرق فاتح', 27.0, 'image/جينزات/جينز مستقيم/jean-straight-3.jpg.png', 'jeans', 'straight', 1, 9, true),
('جينز مستقيم داكن', 29.0, 'image/جينزات/جينز مستقيم/jean-straight-4.jpg.png', 'jeans', 'straight', 1, 10, true),
('جينز مستقيم يومي', 26.0, 'image/جينزات/جينز مستقيم/jean-straight-5.jpg.png', 'jeans', 'straight', 1, 11, true),
('جينز مستقيم مريح', 32.0, 'image/جينزات/جينز مستقيم/jean-straight-6.jpg.png', 'jeans', 'straight', 1, 12, true),
('جينز واسع وفضفاض', 32.0, 'image/جينزات/جينز واسع/jean-wide-1.jpg.png', 'jeans', 'wide', 1, 13, true),
('جينز واسع كاجوال', 30.0, 'image/جينزات/جينز واسع/jean-wide-2.jpg.png', 'jeans', 'wide', 1, 14, true),
('جينز واسع خصر عالي', 34.0, 'image/جينزات/جينز واسع/jean-wide-3.jpg.png', 'jeans', 'wide', 1, 15, true),
('جينز واسع مريح', 29.0, 'image/جينزات/جينز واسع/jean-wide-4.jpg.png', 'jeans', 'wide', 1, 16, true),
('جينز واسع عصري', 33.0, 'image/جينزات/جينز واسع/jean-wide-5.jpg.png', 'jeans', 'wide', 1, 17, true),
('جينز واسع فاتح', 31.0, 'image/جينزات/جينز واسع/jean-wide-6.jpg.png', 'jeans', 'wide', 1, 18, true),
('جينز واسع من الأسفل', 34.0, 'image/جينزات/جينز واسع اسفل/jean-flare-1.jpg.png', 'jeans', 'flare', 1, 19, true),
('جينز فلير كلاسيك', 36.0, 'image/جينزات/جينز واسع اسفل/jean-flare-2.jpg.png', 'jeans', 'flare', 1, 20, true),
('جينز فلير عصري', 33.0, 'image/جينزات/جينز واسع اسفل/jean-flare-3.jpg.png', 'jeans', 'flare', 1, 21, true),
('جينز فلير خصر عالي', 35.0, 'image/جينزات/جينز واسع اسفل/jean-flare-4.jpg.png', 'jeans', 'flare', 1, 22, true),
('جينز فلير داكن', 32.0, 'image/جينزات/جينز واسع اسفل/jean-flare-5.jpg.png', 'jeans', 'flare', 1, 23, true),
('جينز فلير أنيق', 37.0, 'image/جينزات/جينز واسع اسفل/لقطة الشاشة 2026-09-01 144607.png', 'jeans', 'flare', 1, 24, true),
('طقم جيم كامل', 35.0, 'image/اطقم رياضية/رياضية جيم/sport-gym-1.jpg.png', 'sportswear', 'gym', 1, 1, true),
('طقم تمرين ضاغط', 32.0, 'image/اطقم رياضية/رياضية جيم/sport-gym-2.jpg.png', 'sportswear', 'gym', 1, 2, true),
('طقم رياضي احترافي', 38.0, 'image/اطقم رياضية/رياضية جيم/sport-gym-3.jpg.png', 'sportswear', 'gym', 1, 3, true),
('طقم تمرين خفيف', 30.0, 'image/اطقم رياضية/رياضية جيم/sport-gym-4.jpg.png', 'sportswear', 'gym', 1, 4, true),
('طقم جيم ملون', 33.0, 'image/اطقم رياضية/رياضية جيم/sport-gym-5.jpg.png', 'sportswear', 'gym', 1, 5, true),
('طقم تمرين مطاطي', 34.0, 'image/اطقم رياضية/رياضية جيم/sport-gym-6.jpg.png', 'sportswear', 'gym', 1, 6, true),
('طقم رياضي كاجوال', 26.0, 'image/اطقم رياضية/رياضية كاجوال/sport-casual-1.jpg.png', 'sportswear', 'casual', 1, 7, true),
('طقم يومي مريح', 24.0, 'image/اطقم رياضية/رياضية كاجوال/sport-casual-2.jpg.png', 'sportswear', 'casual', 1, 8, true),
('طقم رياضي بسيط', 25.0, 'image/اطقم رياضية/رياضية كاجوال/sport-casual-3.jpg.png', 'sportswear', 'casual', 1, 9, true),
('طقم كاجوال قطن', 27.0, 'image/اطقم رياضية/رياضية كاجوال/sport-casual-4.jpg.png', 'sportswear', 'casual', 1, 10, true),
('طقم يومي عصري', 28.0, 'image/اطقم رياضية/رياضية كاجوال/sport-casual-5.jpg.png', 'sportswear', 'casual', 1, 11, true),
('طقم كاجوال واسع', 23.0, 'image/اطقم رياضية/رياضية كاجوال/sport-casual-6.jpg.png', 'sportswear', 'casual', 1, 12, true),
('طقم رياضي صيفي خفيف', 26.0, 'image/اطقم رياضية/رياضية صيفي/sport-summer-1.jpg.png', 'sportswear', 'summer', 1, 13, true),
('طقم صيفي قصير', 24.0, 'image/اطقم رياضية/رياضية صيفي/sport-summer-2.jpg.png', 'sportswear', 'summer', 1, 14, true),
('طقم صيفي قطن', 25.0, 'image/اطقم رياضية/رياضية صيفي/sport-summer-3.jpg.png', 'sportswear', 'summer', 1, 15, true),
('طقم صيفي فاتح', 27.0, 'image/اطقم رياضية/رياضية صيفي/sport-summer-4.jpg.png', 'sportswear', 'summer', 1, 16, true),
('طقم صيفي بدون أكمام', 23.0, 'image/اطقم رياضية/رياضية صيفي/sport-summer-5.jpg.png', 'sportswear', 'summer', 1, 17, true),
('طقم صيفي مريح', 22.0, 'image/اطقم رياضية/رياضية صيفي/sport-summer-6.jpg.png', 'sportswear', 'summer', 1, 18, true),
('طقم رياضي شتوي دافئ', 36.0, 'image/اطقم رياضية/رياضية شتوي/sport-winter-1.jpg.png', 'sportswear', 'winter', 1, 19, true),
('طقم شتوي بولار', 38.0, 'image/اطقم رياضية/رياضية شتوي/sport-winter-2.jpg.png', 'sportswear', 'winter', 1, 20, true),
('طقم شتوي سميك', 34.0, 'image/اطقم رياضية/رياضية شتوي/sport-winter-3.jpg.png', 'sportswear', 'winter', 1, 21, true),
('طقم شتوي كم طويل', 32.0, 'image/اطقم رياضية/رياضية شتوي/sport-winter-4.jpg.png', 'sportswear', 'winter', 1, 22, true),
('طقم شتوي مبطن', 40.0, 'image/اطقم رياضية/رياضية شتوي/sport-winter-5.jpg.png', 'sportswear', 'winter', 1, 23, true),
('طقم شتوي رياضي كامل', 37.0, 'image/اطقم رياضية/رياضية شتوي/sport-winter-6.jpg.png', 'sportswear', 'winter', 1, 24, true),
('بلوزة قطن كاجوال', 20.0, 'image/بلايز عملية/top-casual-1.jpg.png', 'tops', 'casual', 1, 1, true),
('قميص يومي بسيط', 22.0, 'image/بلايز عملية/top-casual-2.jpg.png', 'tops', 'casual', 1, 2, true),
('بلوزة واسعة كاجوال', 24.0, 'image/بلايز عملية/top-casual-3.jpg.png', 'tops', 'casual', 1, 3, true),
('قميص كاجوال مقلم', 21.0, 'image/بلايز عملية/top-casual-4.jpg.png', 'tops', 'casual', 1, 4, true),
('بلوزة كاجوال باستيل', 23.0, 'image/بلايز عملية/top-casual-5.jpg.png', 'tops', 'casual', 1, 5, true),
('قميص قطن مريح', 19.0, 'image/بلايز عملية/top-casual-6.jpg.png', 'tops', 'casual', 1, 6, true),
('بلوزة صيفي شيفون', 26.0, 'image/ملابس علوية صيفي/top-summer-1.jpg.png', 'tops', 'summer', 1, 7, true),
('قميص صيفي كتان', 25.0, 'image/ملابس علوية صيفي/top-summer-2.jpg.png', 'tops', 'summer', 1, 8, true),
('بلوزة صيفي بدون أكمام', 23.0, 'image/ملابس علوية صيفي/top-summer-3.jpg.png', 'tops', 'summer', 1, 9, true),
('قميص صيفي خفيف', 24.0, 'image/ملابس علوية صيفي/top-summer-4.jpg.png', 'tops', 'summer', 1, 10, true),
('بلوزة صيفي مطبعة', 27.0, 'image/ملابس علوية صيفي/top-summer-5.jpg.png', 'tops', 'summer', 1, 11, true),
('قميص صيفي فاتح', 22.0, 'image/ملابس علوية صيفي/top-summer-6.jpg.png', 'tops', 'summer', 1, 12, true),
('بلوزة شتوي صوف', 34.0, 'image/شتوي/top-winter-1.jpg.jpg', 'tops', 'winter', 1, 13, true),
('قميص شتوي فانيلا', 30.0, 'image/شتوي/top-winter-2.jpg.png', 'tops', 'winter', 1, 14, true),
('بلوزة شتوي سميكة', 36.0, 'image/شتوي/top-winter-3.jpg.png', 'tops', 'winter', 1, 15, true),
('قميص شتوي كم طويل', 29.0, 'image/شتوي/top-winter-4.jpg.png', 'tops', 'winter', 1, 16, true),
('بلوزة شتوي دافئة', 33.0, 'image/شتوي/top-winter-5.jpg.png', 'tops', 'winter', 1, 17, true),
('قميص شتوي مربعات', 28.0, 'image/شتوي/top-winter-6.jpg.png', 'tops', 'winter', 1, 18, true),
('بلوزة هودي شتوية', 28.0, 'image/شتوي/top-winter-7.jpg.png', 'tops', 'winter', 1, 18, true),
('بلوزة محجبات كم طويل', 32.0, 'image/ملابس علوية محجبات/top-modest-1.jpg.png', 'tops', 'modest', 1, 19, true),
('قميص محجبات واسع', 30.0, 'image/ملابس علوية محجبات/top-modest-2.jpg.png', 'tops', 'modest', 1, 20, true),
('بلوزة محجبات طويلة', 35.0, 'image/ملابس علوية محجبات/top-modest-3.jpg.png', 'tops', 'modest', 1, 21, true),
('قميص محجبات كلاسيكي', 28.0, 'image/ملابس علوية محجبات/top-modest-4.jpg.png', 'tops', 'modest', 1, 22, true),
('بلوزة محجبات مطرزة', 38.0, 'image/ملابس علوية محجبات/top-modest-5.jpg.png', 'tops', 'modest', 1, 23, true),
('قميص محجبات أنيق', 31.0, 'image/ملابس علوية محجبات/لقطة الشاشة 2026-08-30 171600.png', 'tops', 'modest', 1, 24, true),
('قميص محجبات أنيق', 31.0, 'image/ملابس علوية محجبات/لقطة الشاشة 2026-08-30 171600.png', 'tops', 'modest', 1, 24, true),
('خاتم فضة أنيق', 15.0, 'image/اكسسوارات/خواتم/acc-rings-1.jpg.jpg', 'accessories', 'rings', 1, 1, true),
('خاتم ذهبي بسيط', 18.0, 'image/اكسسوارات/خواتم/acc-rings-2.jpg.jpg', 'accessories', 'rings', 1, 2, true),
('خاتم مرصع', 22.0, 'image/اكسسوارات/خواتم/acc-rings-3.jpg.jpg', 'accessories', 'rings', 1, 3, true),
('خاتم كلاسيكي', 16.0, 'image/اكسسوارات/خواتم/acc-rings-4.jpg.jpg', 'accessories', 'rings', 1, 4, true),
('سوار فضة', 18.0, 'image/اكسسوارات/اساور/acc-bracelets-1.jpg.jpg', 'accessories', 'bracelets', 1, 5, true),
('سوار ذهبي رفيع', 20.0, 'image/اكسسوارات/اساور/acc-bracelets-2.jpg.jpg', 'accessories', 'bracelets', 1, 6, true),
('سوار جلد', 22.0, 'image/اكسسوارات/اساور/acc-bracelets-3.jpg.jpeg', 'accessories', 'bracelets', 1, 7, true),
('سوار مرصع', 25.0, 'image/اكسسوارات/اساور/acc-bracelets-4.jpg.jpeg', 'accessories', 'bracelets', 1, 8, true),
('ساعة يد كلاسيكية', 45.0, 'image/اكسسوارات/ساعات/acc-watches-1.jpg.jpg', 'accessories', 'watches', 1, 9, true),
('ساعة رياضية', 38.0, 'image/اكسسوارات/ساعات/acc-watches-2.jpg.jpg', 'accessories', 'watches', 1, 10, true),
('ساعة ذهبية أنيقة', 55.0, 'image/اكسسوارات/ساعات/acc-watches-3.jpg.jpg', 'accessories', 'watches', 1, 11, true),
('ساعة سوار جلد', 42.0, 'image/اكسسوارات/ساعات/acc-watches-4.jpg.jpeg', 'accessories', 'watches', 1, 12, true),
('نظارة شمسية كلاسيكية', 25.0, 'image/اكسسوارات/نضارات/acc-glasses-1.jpg.jpg', 'accessories', 'glasses', 1, 13, true),
('نظارة شمسية عصرية', 28.0, 'image/اكسسوارات/نضارات/acc-glasses-2.jpg.jpeg', 'accessories', 'glasses', 1, 14, true),
('نظارة شمسية مربعة', 24.0, 'image/اكسسوارات/نضارات/acc-glasses-3.jpg.jpeg', 'accessories', 'glasses', 1, 15, true),
('نظارة شمسية دائرية', 26.0, 'image/اكسسوارات/نضارات/acc-glasses-4.jpg.jpeg', 'accessories', 'glasses', 1, 16, true),
('سلسلة ذهبية رفيعة', 22.0, 'image/اكسسوارات/سلاسل/acc-chains-1.jpg.jpg', 'accessories', 'chains', 1, 17, true),
('سلسلة فضة كلاسيكية', 20.0, 'image/اكسسوارات/سلاسل/acc-chains-2.jpg.jpg', 'accessories', 'chains', 1, 18, true),
('سلسلة قلادة صغيرة', 24.0, 'image/اكسسوارات/سلاسل/acc-chains-3.jpg.jpg', 'accessories', 'chains', 1, 19, true),
('سلسلة مطعمة', 28.0, 'image/اكسسوارات/سلاسل/acc-chains-4.jpg.jpeg', 'accessories', 'chains', 1, 20, true),
('طقم مجوهرات فضي', 35.0, 'image/اكسسوارات/اطقم/acc-sets-1.jpg.jpg', 'accessories', 'sets', 1, 21, true),
('طقم مجوهرات ذهبي', 42.0, 'image/اكسسوارات/اطقم/acc-sets-2.jpg.jpeg', 'accessories', 'sets', 1, 22, true),
('طقم مجوهرات لؤلؤي', 38.0, 'image/اكسسوارات/اطقم/acc-sets-3.jpg.jpeg', 'accessories', 'sets', 1, 23, true),
('طقم مجوهرات كامل', 48.0, 'image/اكسسوارات/اطقم/acc-sets-4.jpg.jpeg', 'accessories', 'sets', 1, 24, true),
('حلق دائري بسيط', 14.0, 'image/اكسسوارات/حلوق/acc-earrings-1.jpg.jpg', 'accessories', 'earrings', 1, 25, true),
('حلق تعليقة', 16.0, 'image/اكسسوارات/حلوق/acc-earrings-2.jpg.jpg', 'accessories', 'earrings', 1, 26, true),
('حلق مرصع', 20.0, 'image/اكسسوارات/حلوق/acc-earrings-3.jpg.jpg', 'accessories', 'earrings', 1, 27, true),
('حلق كلاسيكي صغير', 13.0, 'image/اكسسوارات/حلوق/acc-earrings-4.jpg.jpg', 'accessories', 'earrings', 1, 28, true),
('فستان صيفي مطبع', 45.0, 'image/item1.jpg', 'featured', '', 1, 1, true),
('حقيبة يد جلد', 35.0, 'image/item2.jpg', 'featured', '', 1, 2, true),
('بلوزة كاجوال', 25.0, 'image/item3.jpg', 'featured', '', 1, 3, true),
('حذاء كعب عالي', 40.0, 'image/item4.jpg', 'featured', '', 1, 4, true),
('ساعة ذهبية', 60.0, 'image/item5.jpg.jpeg', 'featured', '', 1, 5, true),
('بنطلون جينز اسود', 34.0, 'image/item6.jpg.png', 'featured', '', 1, 6, true);